apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
  namespace: canary-playground
  labels:
    app: prometheus

data:
  prometheus.yml: |
    global:
      scrape_interval: 5s
    scrape_configs:
      - job_name: service-a
        metrics_path: /metrics
        static_configs:
          - targets:
              - service-a.canary-playground.svc.cluster.local:80
              - service-a-v1.canary-playground.svc.cluster.local:80
              - service-a-v2.canary-playground.svc.cluster.local:80
      - job_name: service-b
        metrics_path: /metrics
        static_configs:
          - targets:
              - service-b.canary-playground.svc.cluster.local:80
      - job_name: envoy
        metrics_path: /stats/prometheus
        static_configs:
          - targets:
              - envoy-gateway.canary-playground.svc.cluster.local:9901
