apiVersion: apps/v1
kind: Deployment
metadata:
  name: service-a-v2
  namespace: canary-playground
  labels:
    app: service-a
    version: v2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: service-a
      version: v2
  template:
    metadata:
      labels:
        app: service-a
        version: v2
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "8000"
        prometheus.io/path: "/metrics"
    spec:
      containers:
        - name: service-a
          image: canary-playground/service-a:v2
          imagePullPolicy: IfNotPresent
          env:
            - name: SERVICE_VERSION
              value: "v2"
          ports:
            - containerPort: 8000
              name: http
          resources:
            requests:
              cpu: 75m
              memory: 96Mi
            limits:
              cpu: 250m
              memory: 192Mi
          livenessProbe:
            httpGet:
              path: /healthz
              port: http
            initialDelaySeconds: 5
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /healthz
              port: http
            failureThreshold: 2
            periodSeconds: 5
