apiVersion: v1
kind: Service
metadata:
  name: service-a-v2
  namespace: canary-playground
  labels:
    app: service-a
    version: v2
spec:
  selector:
    app: service-a
    version: v2
  ports:
    - name: http
      port: 80
      targetPort: 8000
