apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-datasources
  namespace: canary-playground
  labels:
    app: grafana
    grafana_datasource: "1"
data:
  datasources.yaml: |
    apiVersion: 1
    datasources:
      - name: Prometheus
        type: prometheus
        access: proxy
        url: http://prometheus.canary-playground.svc.cluster.local:9090
        isDefault: true
        jsonData:
          timeInterval: 5s
