apiVersion: v1
kind: Service
metadata:
  name: service-a
  namespace: canary-playground
  labels:
    app: service-a
spec:
  selector:
    app: service-a
  ports:
    - name: http
      port: 80
      targetPort: 8000
