apiVersion: apps/v1
kind: Deployment
metadata:
  name: service-a-v1
  namespace: canary-playground
  labels:
    app: service-a
    version: v1
spec:
  replicas: 2
  selector:
    matchLabels:
      app: service-a
      version: v1
  template:
    metadata:
      labels:
        app: service-a
        version: v1
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "8000"
        prometheus.io/path: "/metrics"
    spec:
      containers:
        - name: service-a
          image: canary-playground/service-a:v1
          imagePullPolicy: IfNotPresent
          env:
            - name: SERVICE_VERSION
              value: "v1"
          ports:
            - containerPort: 8000
              name: http
          resources:
            requests:
              cpu: 50m
              memory: 64Mi
            limits:
              cpu: 200m
              memory: 128Mi
          livenessProbe:
            httpGet:
              path: /healthz
              port: http
            initialDelaySeconds: 5
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /healthz
              port: http
            initialDelaySeconds: 3
            periodSeconds: 5
