global:
  scrape_interval: 5s

scrape_configs:
  - job_name: service-a
    metrics_path: /metrics
    static_configs:
      - targets:
          - service-a-v1:8000
          - service-a-v2:8000
  - job_name: service-b
    metrics_path: /metrics
    static_configs:
      - targets:
          - service-b:8000
  - job_name: envoy
    metrics_path: /stats/prometheus
    static_configs:
      - targets:
          - envoy:9901
