apiVersion: v1
kind: Service
metadata:
  name: prometheus
  namespace: canary-playground
  labels:
    app: prometheus
spec:
  type: NodePort
  selector:
    app: prometheus
  ports:
    - name: http
      port: 9090
      targetPort: 9090
      nodePort: 30001
